name: dogs_toml
description: Toml serializer for the dogs graph serializer
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dogs_core: ^1.0.0-alpha
  toml: ^0.13.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
