name: dogs_darwin
description: Darwin marshal linker for the dogs serialization library.
version: 1.0.0
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  darwin: any
  darwin_marshal: any

  dogs: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
