name: dogs_cbor
description: Cbor serializer for the dogs graph serializer
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cbor: ^5.1.2
  dogs_core: ^1.0.0-alpha

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
