name: dogs_core
description: a universal serialization library using code generation to reduce boilerplate massively.
version: 1.0.0-alpha
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  aqueduct_isolates: ^1.0.1
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
